name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm run test
        env:
          CI: true
